name: Pre-Validation on Developer Sandbox

on:
    push:
        paths:
            - 'force-app/**'
        branches:
            - feature/*
            - bugfix/*
            - hotfix/*
    pull_request:
        branches:
            - develop

jobs:
    prevalidate:
        runs-on: ubuntu-latest
        environment: developer
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.1.7
              with:
                  fetch-depth: 0

            - name: Install npm dependencies
              run: npm install

            - name: Linting Check
              run: npm run lint

            - name: Unit Test Check
              run: npm run test
