name: Pre-Validate Dev Sandbox
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]
        paths:
            - 'force-app/**'
        branches:
            - develop

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: developer
        steps:
            - name: 'Validation Job Message'
              run: echo "Starting Validation for Dev Sandbox"

            - name: Checkout Code
              uses: actions/checkout@v4.1.7
              with:
                  fetch-depth: 0

            - name: Install npm dependencies
              run: npm install

            - name: Install Salesforce CLI
              run: npm install @salesforce/cli --global

            - name: Decrypt the server.key.enc file
              run: openssl enc -nosalt -aes-256-cbc -d -in ${{ secrets.ENCRYPTED_KEY_FILE }} -out ${{ secrets.JWT_KEY_FILE }} -base64 -K ${{ secrets.KEY }} -iv ${{ secrets.IV }}

            - name: Authorize with Salesforce org
              run: sf org login jwt --username ${{ secrets.DEV_USERNAME }} --jwt-key-file ${{ secrets.JWT_KEY_FILE }} --client-id ${{ secrets.SF_CLIENT_ID }} --set-default --alias ci-org --instance-url ${{ secrets.SF_INSTANCE_URL }}

            - name: Validate Code in Dev Sandbox
              run: sf project deploy validate --source-dir force-app --target-org ci-org
