name: Dev Pipeline
run-name: ${{github.actor}} running this pipeline 🚀
## pipeline will be running in 2 events
## pull, push request
on: [push, pull_request]
jobs:
    build-and-deploy: ## name of the job
        runs-on: ubuntu-latest ## runner
        steps:
            - run: echo "Hello, world!" ## step 1
              name: 'First Job'
            - name: Checkout Code
              uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0
            - name: npm install
              run: npm install

    clean-up: ## name of the job
        runs-on: ubuntu-latest ## runner
        steps:
            - run: echo "Clean up the resources" ## step 1
              name: 'Second Job'
